### ISSUE TITLE
How do I make Igbo to english translation worK

### ISSUE THREAD

**Issue by prondubuisi** [apertium/apertium-eng-ibo#4]
According to the Readme.md file running both

`$ echo "house" | apertium -d . eng-ibo
`
and

` $ echo "akpa" | apertium -d . ibo-eng`
Should work but this is not the case after running the make command, The `eng-ibo` works, but the `ibo-eng` doesn't work, how do I fix this? Below is a screen shot
![Apertium](https://user-images.githubusercontent.com/22311928/77555043-1ba39f80-6eb7-11ea-9339-2fa8730d4244.png)

**Comment by IlnarSelimcan** [comment]
Hi @prondubuisi ! Have you been able to get the output that you expect?

This is the output I get when using the latest revision https://github.com/apertium/apertium-eng-ibo/commit/a2cee8dd6e543b4d019735ffa84b12e1696ff3de : 

```
apertium-eng-ibo$ echo "ụlọ" | apertium -d . ibo-eng
#house
```

**Comment by prondubuisi** [comment]
Hello @IlnarSelimcan I still get the same output even after pulling in your changes, is there anything I should do differently 
![Apertium](https://user-images.githubusercontent.com/22311928/83320869-2b3abe00-a243-11ea-8cb2-a023103c8e33.png)

**Comment by IlnarSelimcan** [comment]
@prondubuisi does running `echo "ụlọ" | apertium -d . ibo-morph` in apertium-ibo work?

```
echo "ụlọ" | apertium -d . ibo-morph
^ụlọ/ụlọ<n>$
```
Make sure that you are typing in exact same characters for `ụlọ` as it is written in https://github.com/apertium/apertium-eng-ibo/blob/master/apertium-eng-ibo.eng-ibo.dix

Unfortunately from the screenshot I can't lookup the characters you typed in a unicode-table ;)

**Comment by prondubuisi** [comment]
Hello @IlnarSelimcan sorry for the delay in response, this is the output on apertium-ibo
```
prondubuisi@prondubuisi:~/gitrepos/apertium-ibo$ echo "ụlọ" | apertium -d . ibo-morph
^ụlọ/ụlọ<n>$
```

Here is the output from `apertium-eng-ibo`
```
prondubuisi@prondubuisi:~/gitrepos/apertium-eng-ibo$ echo "ụlọ" | apertium -d . ibo-eng
*ụlọ

 
```

**Comment by IlnarSelimcan** [comment]
It'd be easier / faster to debug this if you join our IRC channel: https://wiki.apertium.org/wiki/IRC

**Comment by prondubuisi** [comment]
Yeah @TinoDidriksen always helped with issues on IRC, do I need to post a link to this issue there?
